containerized: "oras://ghcr.io/erfanshekarriz/vomix:v0.1.0-beta.1"

import os
import sys
import json
import datetime
from typing import Union, List

sys.path.insert(0, os.path.join(workflow.basedir, "scripts"))
import vomix_utils
import vomix_modules
from vomix_utils import cleanpath, relpath, fullpath
from vomix_parse_samples import parse_sample_list

from snakemake.utils import validate

configfile: "config/config.yml"
workdir: config["workdir"]
config["basedir"] = workflow.basedir

# Validate config
validate(config, "../config/config.schema.yml")

# Set global context for vomix_utils
vomix_utils.config = config
vomix_outdir = config["outdir"]
vomix_utils.outdir = vomix_outdir

# Set database paths absolute relative to basedir
db_list = [key for key in config if key.endswith("db")]
vomix_utils.update_db_paths(db_list)

# Clean directory paths for basic inputs
vomix_utils.clean_config_paths(["samplelist", "datadir", "outdir", "fasta", "fastadir"])

# Setup the output directory and its .vomix subdirectory
vomix_utils.setup_output_dir(vomix_outdir)

# Ensure only one input provided to break ambiguity (samplelist | fasta | fastadird)
vomix_utils.validate_input_count(config)

# Save configuration file
vomix_utils.save_config_file(config, vomix_outdir)

# Set final post-validated variables
samplelist = config.get("samplelist")
datadir = config.get("datadir")
outdir = config.get("outdir")
fasta = config.get("fasta")
fastadir = config.get("fastadir")

# Set wildcard constraints
wildcard_constraints:
    sample_id = "[A-Za-z0-9_-]+"

# ----------------------------------------------------------------------
# Include modules and collect targets
# ----------------------------------------------------------------------
for vomix_module in vomix_modules.ALL_MODULES:
    if vomix_module.should_run(config):
        vomix_module.setup(config, outdir)
        for smk_file in vomix_module.snakemake_files:
            include: smk_file
        vomix_module.add_targets()

# ----------------------------------------------------------------------
# Master rule
# ----------------------------------------------------------------------
rule all:
    input: vomix_utils.targets