name: vomix-mega
channels:
  - conda-forge
  - bioconda
  - defaults
platforms:
  - linux-64
  - linux-aarch64
  - osx-64
  - osx-arm64
dependencies:
  - python>=3.10
  - pip
  - click>=8
  - rich-click>=1.5
  - snakemake>=9.23.1
  - biopython>=1.84
  - snakemake-executor-plugin-cluster-generic>=1.0.9
