name: vomix
channels:
  - conda-forge
  - bioconda
  - defaults
platforms:
  - linux-64
  - linux-aarch64
  - osx-64
  - osx-arm64
dependencies:
  - python>=3.12,<3.14
  - pip
  - click>=8,<9
  - rich-click>=1.5,<2
  - snakemake>=9.23.1,<10
  - biopython>=1.84
  - snakemake-executor-plugin-cluster-generic>=1.0.9,<2
